name: CI (mouse PE ST data)
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
    steps:
      - uses: actions/checkout@v2
      - name: Crean env
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull myoshimura080822/ramdaq:v1.2
      - name: Run pipeline with test data
        run: |
          # TODO: You can customise CI pipeline run tests as required
          # (eg. adding multiple test runs with different parameters)
          # nextflow run ${GITHUB_WORKSPACE} -profile test,docker
          nextflow run ${GITHUB_WORKSPACE} -profile test_PE_ST_M,docker
      - name: Deploy to ramdaq-mouse-pe-st.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'ramdaq-mouse-pe-st.surge.sh'
          project: './results/MultiQC'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}